# These are supported funding model platforms

github: [wawerumb-ux]
patreon: Dev-sling
open_collective: 
ko_fi: devsling
tidelift: 
community_bridge: 
liberapay: 
issuehunt: 
lfx_crowdfunding: 
polar: 
buy_me_a_coffee: devsling
thanks_dev: wawerumb-ux
custom: ['https://www.buymeacoffee.com/devsling', 'https://github.com/sponsors/wawerumb-ux']
